### PR TITLE
update sigcheck.c

### PR DESCRIPTION
**Pull request by pyj2323**
to make "DbgPrint" macro effective

### CODE REVIEW

**Review by cheat-engine — COMMENTED** [review]
I need the dbgprint in release for users that have tampered with the .exe

**Review by cheat-engine — APPROVED** [review]

**Review by cheat-engine — COMMENTED** [review]
that will break on low memory systems where the structure gets paged out right before vmcall. 
it's better to use a 2nd or 3th register for password then

**Comment by pyj2323** [comment]
So, would you like to add 2nd or 3th register for password?

**Comment by cheat-engine** [comment]
yeah , perhaps a 3th parameter, and perhaps increase the password size to 64-bit, and if you specify a bit in the high range you knowingly disable 32-bit caller support

and perhaps a specific runtime flag that can disable the pagefault check if you insist

**Pull request closed without merging**
