### PR TITLE
more clear install instructions

### PR DESCRIPTION
**Pull request by Axelfoley85**
Relates to https://github.com/cheat-engine/cheat-engine/issues/2640

### CODE REVIEW

**Comment by Axelfoley85** [comment]
relates to https://github.com/cheat-engine/cheat-engine/issues/2640

**Comment by fade2gray** [comment]
You could have changed it to use ...
`lazarus-2.2.6-fpc-3.2.2-win64.exe` and `lazarus-2.2.6-fpc-3.2.2-cross-i386-win32-win64.exe`
😉

**Comment by Axelfoley85** [comment]
> You could have changed it to use ... `lazarus-2.2.6-fpc-3.2.2-win64.exe` and `lazarus-2.2.6-fpc-3.2.2-cross-i386-win32-win64.exe` 😉

Are these tested properly already?

Kinda would prefer to clear the README first if anybody later decides to roll back purely on the version change or sth.

I can open a second PR for the version upgrade, too.

**Comment by fade2gray** [comment]
I've been using v2.2.6 since it was released March 2023. I know v3.0 and v3.2 do not work, but I haven't tried v3.4 yet.

**Comment by Axelfoley85** [comment]
@fade2gray Alright, your call now!

**Pull request closed without merging**
