### PR TITLE
Fix typo 'seperate' to 'separate'

### PR DESCRIPTION
**Pull request by korcankaraokcu**

### CODE REVIEW

**Comment by korcankaraokcu** [comment]
@cheat-engine What's the problem?

**Comment by cheat-engine** [comment]
This is the result of a search and replace operation.  
Many files including third party sourcefiles have been modifed, formdefinitions , unusefd files and even binary files have been changed

(and most are just comments or internal functionnames.)

There can go too many things wrong by accepting a full request like this.

Best just do pull requests for things that actually affect the program like GUI typos

**Comment by korcankaraokcu** [comment]
Fair enough. I'll update my commit tomorrow. I noticed that typo only in one GUI element anyway, should be a small patch

**Comment by korcankaraokcu** [comment]
@cheat-engine Aight, updated my fork. Reopening this pull request should update the commit for you as well. Only GUI files are modified now

**Comment by cheat-engine** [comment]
I can't reopen: "The typo fix branch was force-pushed or recreated" (and it still shows the old)

**Comment by korcankaraokcu** [comment]
Oh right, I had to force-push since I overwrote my faulty commit. Github normally automatically updates the PR if the fork is updated as well, except if the PR is closed and the fork is force-pushed. So, please don't close the PRs right away. Instead, request changes from the PR owner if the intention of the PR is useful. This typo fix wasn't that important tho. Also, as you said, languages are malleable, once enough people use seperate it will officially become seperate. I've noticed that I was using the word separate wrong for many years as well, probably because of the pronounciation. Sorry for taking this long to reply btw, have a nice day

**Pull request closed without merging**
