### PR TITLE
ShowColorPicker Implementation (+lua)

### PR DESCRIPTION
**Pull request by supMarco**
What do you think?

### CODE REVIEW

**Comment by cheat-engine** [comment]
i don't know. I don't think a new form is needed for that. perhaps just the colorpicker control and then create a new form with a colorpicker

**Comment by supMarco** [comment]
oh, I gotcha
nevermind then (shall I close this pull request?)

**Comment by mgrinzPlayer** [comment]
```Lua
ColorDialog = createComponentClass('TColorDialog', MainForm)

if ColorDialog.execute() then
  MainForm.Panel5.Color = ColorDialog.Color
end

ColorDialog.destroy()
```

**Comment by supMarco** [comment]
looks neat, let me test that

**Comment by supMarco** [comment]
indeed, works like a charm.  :woman_facepalming:

**Comment by supMarco** [comment]
ps: before ending up doing more stupid stuff, 
Cattura
will this just 'undo' the changes? or will it erase the whole file lol?

**Comment by mgrinzPlayer** [comment]
I suggest making branches for all your pull requests.

I personally have main branch which is 100% exact copy of main branch 'master' from here.
(I renamed mine to mgrinz_master :-) )

I update this branch from time to time like this:
- choose your main branch (e.g. mgrinz_master)
- click "fetch origin" and/or "pull...." button (if you work on 2+ computers)
- from menu choose "branch" -> "merge into current branch", and from the list choose "upstream/master", click "merge" button. It will take all current commits from cheat-engine/cheat-engine/master
- then click "push origin"

When you want to make some changes, create new branch based on your just updated "master".
Click "branch" -> "new branch"

Make some changes, commit those changes to just created branch, click "publish", then "push", then "branch" -> "create pull request".

That way you can evade those "revert commits" and "Merge branch 'master'" mess.

**Comment by supMarco** [comment]
You're a lifesaver, thanks a bunch man 

(Gonna try that straight away)

**Comment by mgrinzPlayer** [comment]
I ended up with 90 branches...

**Comment by supMarco** [comment]
mgrinz
@mgrinzPlayer

**Comment by mgrinzPlayer** [comment]
Choose "upstream/master", then create new branch based on "upstream/master". you can name it  "supMarco_master". 

Then go here: https://github.com/supMarco/cheat-engine/settings/branches
and change the default branch.

then go to https://github.com/supMarco/cheat-engine/branches and remove not needed branches.

**Comment by supMarco** [comment]
I finally managed to do it lol: https://github.com/supMarco/cheat-engine/branches

also I noticed your unlimited branches :stuck_out_tongue: : https://github.com/mgrinzPlayer/cheat-engine/branches/stale

**Comment by mgrinzPlayer** [comment]
Next time if your PR is not "approved" or it becomes "outdated" you can just close PR. Remove the branch, then create new one based on "upstream/master" or updated "supMarco_master", you can even use the same name as the recently removed one.

**Pull request closed without merging**
