### PR TITLE
changed 'Show invisible windows' to 'Refresh list' + shortcut

### PR DESCRIPTION
**Pull request by supMarco**

### CODE REVIEW

**Comment by cheat-engine** [comment]
Some people really need the invisible window list so that's not an option. If you want a refresh then add a new item, don't delete an existing feature

**Comment by supMarco** [comment]
All it does is:
Cattura

ok though

**Comment by cheat-engine** [comment]
miShowInvisibleItems is an autocheck menuitem, so if you select it it's .checked property switches
GetWindowList(list,showVisible)  gets that flag and returns a different list depending on that status

**Comment by supMarco** [comment]
damn, my bad -.- I didn't notice it
going to reset my fork

**Pull request closed without merging**
