### PR TITLE
Add SAL Instructions for disassembly

### PR DESCRIPTION
**Pull request by CJBok**
Source:
http://www.capstone-engine.org/

### CODE REVIEW

**Comment by cheat-engine** [comment]
According to https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf SAL is /4

there is no D1 /6

**Comment by CJBok** [comment]
> According to https://software.intel.com/content/dam/develop/external/us/en/documents-tps/325383-sdm-vol-2abcd.pdf SAL is /4
> 
> there is no D1 /6
> 
> (

This is a problem in the intel documentation. (SHL and SAL or both using /4 according to the doc)
This would also explain why there is a gap between /5 and /7

/4 SHL
/5 SHR
/6 SAL
/7 SAR


**Did some testing in cheat engine**
r9 = 03

Instruction: 41 C1 F1 02 - Multiply r9d by 2, 2 times
Result: r9 = 0C (12)

**Comment by cheat-engine** [comment]
SHL and SAL are apparently the same implementation wise.  I guess a long time ago both where implemented separately but Intel and AMD seem to have decided to ignore the documentation of the /6 implementation of SAL.  I'll add the disassembler code so it recognizes it, but the assembler will still generate the SHL bytecode for SAL

**Comment by CJBok** [comment]
Resolved: https://github.com/cheat-engine/cheat-engine/commit/c36340446ade54ede51933352e5d6a333aba73ba

**Pull request closed without merging**
