### PR TITLE
License

### PR DESCRIPTION
**Pull request by Maniues**
You're using some GNU GPL'ed software.
Please change license of CE to GNU GPL (just confirm this PR)

### CODE REVIEW

**Comment by cheat-engine** [comment]
Tcc is distributed under the lgpl .  It's library sourcecode is available and under the lgpl, the rest of the repository is not

**Comment by Maniues** [comment]
> 
> 
> Tcc is distributed under the lgpl . It's library sourcecode is available and under the lgpl, the rest of the repository is not

See this https://github.com/cheat-engine/cheat-engine/issues/60
There are some files under GPL.

Additionally GPL comply with your agreements (in practice):
You may mod games with CE but not distribute games moded with it - GPL requires redistributing source code. Any redistribution of the game may be illegal.
You are using some GPL'ed software.
Now, i'm only say "Please change license to GPL", but I can contact with FSF or other copyright owners of the software you use.
I don't want to do that, because they can be agressive (in legal meaning).
GPL makes that CE will be more available and you won't be liable for any illegal use.
DON'T PROTECT BIG CORPORATIONS (game developers). They have a lot of lawyers. They will ignore you.
In practice, users that use your software for illegal use, break law. Why you want to stop them with your license.
If someone break the law (breaking DRM etc.), that person will violate your copyrights too. Your license won't stop it. 
For pirates license is nonsense and they will break it.

**Comment by Veratyr** [comment]
@cheat-engine you can't use any other Licence rather than GPL-compatible, because Cheat Engine already contains GPL-licensed code. It automatically makes all Cheat Engine code GPL licensed.

**Comment by ThisGitHubUsernameWasAvailable** [comment]
@cheat-engine you can't use any other Licence rather than GPL-compatible, because Cheat Engine already contains GPL-licensed code. It automatically makes all Cheat Engine code GPL licensed.

**Comment by aloisdg** [comment]
@RobertDeRose Check #60 (i.e. https://github.com/cheat-engine/cheat-engine/issues/60#issuecomment-942071225)

**Comment by nothere12345** [comment]
https://lists.nongnu.org/archive/html/tinycc-devel/2013-05/msg00012.html

**Comment by lawl** [comment]
See the discussion on the orange website here: https://news.ycombinator.com/item?id=31084128

I believe there's no issue here, the only possibly problematic file is [il-opcodes.h](https://github.com/mirror/tinycc/blob/mob/il-opcodes.h) which has been fully authored by Fabrice Bellard [see git blame](https://github.com/mirror/tinycc/blame/mob/il-opcodes.h).

However, there seems to be a relicencing effort to a permissive license going on anyways to which Fabrice Bellard already agreed; https://github.com/mirror/tinycc/blob/mob/RELICENSING

Thus arguably, this file is already dual licensed and there is no problem.

**Comment by cheat-engine** [comment]
Let's just close this.  The libraries uses are LGPL and and other non-gpl.  I've waited long enough and no copyrightholder has filed a claim yet. If for some reason the RELICENSING file of libtcc is deemed invalid, then Fabrice Bellard is free to contact me to request the removal of the libtcc library usage in this project.  (Still, CE is not going to be GPL)

**Comment by Maniues** [comment]
To be honest, I ignored the subject of reporting copyright infringement. I just took the time to do other worthwhile projects to help me grow. Like CE, it helps mod makers and other RE engineers to grow.
It would be of no benefit to anyone to report a copyright infringement. I would waste time writing the right letter and documenting the entire repo, copyright owners would waste time reading this and possibly intervening without getting anything, and you @cheat-engine would waste time deleting these libraries and looking for replacement ones. Engineers would lose their tools for doing their work for a while, use older versions, or have to download some library files separately. Looking after your statements, for some reason you will not release CE as a Free Software / Open Source application. You make an application for people who want to be creative, modify the application while partially blocking the use of a specific tool to do it.
Somehow I'm not desperate to try to force you to change the license or block the development of this software. The only thing I ask you @cheat-engine is to establish a license in the main project folder so that everyone can clearly see under what conditions CE is.
I also ask you to mark on the CE pages and in this repo that this is not Open Source or Free Software.
Maybe someday you decide to Open-Source this code.

P.S (I don't want to do a separate thread for it) in order to upload someone else's contributions that he made available to you through PR, you should add information about the licensing conditions for you as a creator to use these contributions. You can do it yourself, eg through the MIT license, you can also contact me so that I can help you (yes, I am able to help you selflessly. I prefer proprietary software than software that uses other people's work in some strange way). You can just tag me in a discussion or PR then.

**Pull request closed without merging**
