### PR TITLE
TformAddressChange resizing

### PR DESCRIPTION
**Pull request by mgrinzPlayer**
Adds two buttons to the form. Clicking + button will resize all edit controls by one char.
Holding ctrl key and clicking + button will resize all edit controls by four char.

### CODE REVIEW

**Comment by cheat-engine** [comment]
what do you think of the current squishy implementation ?

**Comment by mgrinzPlayer** [comment]
Looks nice when adding new entry or pointer. With baseAddress TEdit it would be perfect.

Small issue while editing existing pointers is broken.
obraz
obraz

Also sbDecrease sbIncrease have wrong size, can be fixed with those lines inside settop
```
  sbDecrease.Width:=edtOffset.Height;
  sbDecrease.Height:=edtOffset.Height;
  sbIncrease.Width:=edtOffset.Height;
  sbIncrease.Height:=edtOffset.Height;
```

My 'ptach' could be a "hidden" feature... or something. Or maybe saving TformAddressChange position and size (with height ignored)

**Comment by cheat-engine** [comment]
How about now ?

**Comment by mgrinzPlayer** [comment]
Looks good.

**Comment by mgrinzPlayer** [comment]
Reopening this as issue. When editing existing address, editAddress width is not updated after LoadFormPosition - it stays small.

**Comment by cheat-engine** [comment]
should be fixed now

**Comment by mgrinzPlayer** [comment]
thank you

**Pull request closed without merging**
