### PR TITLE
PR to allow a block of hex text to be entered into find window for array search

### PR DESCRIPTION
**Pull request by pinchyCZN**
this change allows a block of text in hex format with unknown delimiters to be entered into the search window.
Hex data such as this can be pasted from some hex editor into the find window:
17 00 00 00-CB D4 EF 31-EC 1E 73 C7-8E 93 EC C1
1B FE 0E 56-10 D5 D9 83-55 A6 35 17-00 00 00 02
0B B3 FB 06-30 F4 FF B9-5F 20 8A 3C-3C B6 5D A3

also added a grip resize control but not sure how cross platform compatible it is. I never can get the status bar control with its gripper to be sized properly on the form.

Might be able to just remove the progress bar and move the ok/cancel buttons up and put a status bar across the entire bottom

### CODE REVIEW

**Comment by pinchyCZN** [comment]
Another idea would be to have both a single and multiline edit control on the form and set them visible as required when the radio button is selected.

**Comment by pinchyCZN** [comment]
I decided to have a single line and multiline edit control and change visibility depending on the radio button. Also got rid of the progress bar and used a status bar with gripper instead. Seems like the progress bar wasnt used. Instead I just set the status to "searching" when starting the search.

**Comment by mgrinzPlayer** [comment]
Hi, can you tell me which Lazarus version are you using?

Why I am asking? Because, if DB didn't updated his environment, I and he are using Lazarus 1.6.4 with those patch:
https://github.com/cheat-engine/cheat-engine/issues/77#issuecomment-302165307

I see a lot of small, and not useful, changes inside LFM files in your PR requests, such as
```diff
-      Height = 15
+      Height = 13
```

**Comment by pinchyCZN** [comment]
Im using 1.6.4. Whats the TLDR version of the fixes to lazarus from that mentioned thread? From what I gather you have to replace some source files and recompile some libraries? Will that fix the form editor from changing the dimensions of various controls?

Ive seen similar problems with delphi 7 that I use at work. For some reason it will change the item height of combo boxes and other things similar to above. It might have to do with the desktop theme fonts and DPI. It must be trying to rescale the dialog units to what it thinks are defaults.

**Comment by mgrinzPlayer** [comment]
For 1.6.4 we use the patch I wrote on 17 May:
https://github.com/cheat-engine/cheat-engine/issues/77#issuecomment-302165307

It fixes

1) "Dissect Structure" item multi selecting. Without the fix you will have:
- when you select first entry, then scroll down (so this entry is not visible) and select last entry (with left click and SHIFT key pressed) treeview will scroll vertical automatically so last entry will be at the bottom.
- when you select first entry, then scroll up (so this entry is not visible) and select last entry (with left click and SHIFT key pressed) treeview will scroll vertical automatically so last entry will be at the top. 

2) header control mouse cursor locks 

3) minimizing form issues (e.g. minimizing "trainer generator" window will freeze CE; endless loop)

4) multiple screen crashes (when CE is used for a very long time and monitor(s) are plugged/unplugged)

**Pull request closed without merging**
