### PR TITLE
Improve README.md

### PR DESCRIPTION
**Pull request by Margen67**
Add logo to top.
Separate Download, Links, etc into sections.
Remove giant Download button.
Made Latest version download link automatically go to latest release;
I'm not sure if binaries can be linked to this way, but it makes it easier to release new version(s).
Add Patreon and PayPal donation links.
Make Build and Contributing instructions into numbered steps.
Minor grammar/spelling fixes.
Make all links https.

### CODE REVIEW

**Comment by nik0la-vr** [comment]
You might want to add that FPC 3.2.0 snapshot is needed for compilation. Download link would be appreciated.

**Comment by Margen67** [comment]
Will this work? https://sourceforge.net/projects/lazarus-snapshots/files/Window%2064/lazarus-2.0.4-61666-fpc-3.2.0-beta-42593/

**Comment by mgrinzPlayer** [comment]
FPC from https://svn.freepascal.org/svn/fpc/branches/fixes_3_2 revision 42444
Lazarus 2.0.0
source - https://github.com/cheat-engine/cheat-engine/issues/822#issuecomment-520377780

if you want as much similar as possible to original binary.

I can upload my compiled FPC 3.2.0 rev 42444 if you want.
obraz

**Comment by Margen67** [comment]
@mgrinzPlayer I would like for you to upload the compiled FPC.

**Comment by mgrinzPlayer** [comment]
7zipped and on mega.nz ?

**Pull request merged**
