### PR TITLE
[CI] Add GitHub Actions

### PR DESCRIPTION
**Pull request by Margen67**
64 and 32 bit are built seperately.
xmplayer is deleted for 64 bit builds due to it not supporting 64 bit.

Example run: https://github.com/Margen67/cheat-engine/commit/9fc94b50e56e99f50da9b2d6d80f8fe11d17b7db/checks

Also delete AppVeyor which wasn't installed, and wouldn't have worked anyway.

Credits:
coast77777777777 for the appveyor.yml which this is based off of.
weide-zhou from the GitHub Actions forum for helping: https://github.community/t5/GitHub-Actions/Getting-error-with-workflow-file/m-p/36802#M2689
https://sourceforge.net/projects/lazarus-snapshots/

### CODE REVIEW

**Comment by Margen67** [comment]
@cheat-engine 👀

**Comment by mgrinzPlayer** [comment]
I think it is a good idea. But, not for this main repo. Maybe another repo/mirror. Because, currently, we can not delete old workflow results. The only way, I think, is by removing whole repo and recreate it from the scratch. Deleting a branch is not enough. Here you can see results from branches I made for learning:
https://github.com/mgrinzPlayer/cheat-engine/actions
There are results from already removed "testAction", "ACTIONS, "Action_compile_official_Lazarus206".

I do not see a way to leave only results from those:
- "Custom_Lazarus_FPC_Action" here:
Lazarus2.0.0 with FPC3.2.0Beta from fixes_3_2 branch revision 42444
https://github.com/mgrinzPlayer/cheat-engine/blob/Custom_Lazarus_FPC_Action/.github/workflows/main.yml


- and "Official_Lazarus206_Action" there:
official Lazarus2.0.6
https://github.com/mgrinzPlayer/cheat-engine/blob/Official_Lazarus206_Action/.github/workflows/main.yml


Both workflows uses already installed(or compiled) Lazarus, cleaned, prepared as "portable" (), compressed.

**Comment by Margen67** [comment]
@mgrinzPlayer Should I close this PR?

**Comment by mgrinzPlayer** [comment]
It's not my call. Ask @cheat-engine

**Comment by cheat-engine** [comment]
I don't know, but just leave it up for now so I can check it out if I decide so in the future

**Comment by Margen67** [comment]
This is a very hacky way of building and uses an unofficial Lazarus/FPC, so I think it would be best to wait for an official new release for Lazarus.

**Pull request closed without merging**
