### PR TITLE
Changed Lua script errors to give correct AA line numbers (not {$lua} relative)

### PR DESCRIPTION
**Pull request by Measurity**
Before:
image

After:
image

Script:
image

### CODE REVIEW

**Comment by cheat-engine** [comment]
The error should have 2 line numbers.  The AA script error and the Lua script error.
The AA script error is the location of the Lua script start.  (it's return value will be placed at that point)

The Lua script error is relative to the start of the script, but that one is off by 1, but it's generated by lua, not CE.   You could probably scan the error message for the linenumber and decrease it by 1

example script:
```
[enable]
//AA line 2
//AA line 3
{$lua}
--this
--is
--filler
error('meh') --should be line 4 (or AA line 8) but shows as 5)

{$asm}
//AA line 11
00400500:
nop
nop
nop
db 'humbug'

[disable]
```

**Comment by Measurity** [comment]
Made the changes. I'm not sure if I can safely replace all numbers in the lua error message so I limited it to the first `number:` part. Other references to line numbers will still be off. Example:
image

```
{$STRICT}

[ENABLE]
{$lua}
--AOBCache:aobSymbol('pFOV', 'F30F1183A8010000')
registerSymbol('pFOV', 'bla',3


{$asm}
alloc(newmem,$1000,pFOV)

label(code)
label(return)
label(fFOV)
registersymbol(fFOV)

newmem:
  movd xmm0,[fFOV]
code:
  movss [rbx+000001A8],xmm0
  jmp return
fFOV:
  dd (float)90.0

pFOV:
  jmp newmem
  nop 3
return:

[DISABLE]

pFOV:
  db F3 0F 11 83 A8 01 00 00

unregistersymbol(fFOV)
dealloc(newmem)
```

**Comment by cheat-engine** [comment]
The first part line number was actually correct. It's referencing the script that starts at the given linenumber. (i guess the more clear text should be :"error in the lua script starting at line x")

**Comment by Measurity** [comment]
Afaik: It keeps scanning until it knows for sure there's an error (with this syntax error is at the `{$asm}`). 
If it finds the error earlier it makes more sense:
image

**Pull request closed without merging**
