### PR TITLE
about dbvm password

### PR DESCRIPTION
**Pull request by pyj2323**

### CODE REVIEW

**Comment by cheat-engine** [comment]
why the change in internal_LaunchDBVM ? It has already been parsed by dbkinitialize, and this ignores changes to the password after loading CE using dbvm_setKeys

**Comment by pyj2323** [comment]
Current CE does not set password from driver64.dat when load dbvm.

**Comment by cheat-engine** [comment]
It does in dbkinitialize update your driver64.dat file if you have one.  password 3 got added to it

**Comment by pyj2323** [comment]
When CE open, configure_vmx called with param password from driver64.dat. but configure_vmx function reset password. this is bad

**Comment by cheat-engine** [comment]
configure_vmx should not change it anymore

**Pull request closed without merging**
