### PR TITLE
Enable Appveyor Continuous Integration #248

### PR DESCRIPTION
**Pull request by coast77777777777**
Greetings,

This commit adds support for autonomous build for each commit to the repo.
Resolves Issue https://github.com/cheat-engine/cheat-engine/issues/248

for build log REF: https://ci.appveyor.com/project/mancoast/cheat-engine
for zip artifacts REF: https://ci.appveyor.com/project/mancoast/cheat-engine/build/artifacts

To utilize the CI, add link this repo from Github to Appveyor.

Thanks,
coast

### CODE REVIEW

**Comment by Margen67** [comment]
@cheat-engine 👀

**Comment by cheat-engine** [comment]
Still not sure how to implement and update this (e.g different lazarus and fpc build at the moment)

**Comment by Margen67** [comment]
Do you mean update it to the latest larzarus/fpc version?

**Comment by cheat-engine** [comment]
and how to use it to begin with

**Comment by coast77777777777** [comment]
If you merge, I will maintain. This system has legitimate use in reversing sega and other retro games for inclusion in openAI gym.

**Comment by cheat-engine** [comment]
alright

**Pull request merged**
